### ISSUE TITLE
local server connection fails

### ISSUE THREAD

**Issue by shencebebetterme** [karpathy/arxiv-sanity-preserver#91]
Hi,
an error occurs when I run serve.py , something seems wrong with the `.count()` attribute. I commented out the tweets related lines because tweets is blocked by the internet censorship, the relevant codes are like:

```python
  print('connecting to mongodb...')
  client = pymongo.MongoClient()
  mdb = client.arxiv
  #tweets_top1 = mdb.tweets_top1
  #tweets_top7 = mdb.tweets_top7
  #tweets_top30 = mdb.tweets_top30
  comments = mdb.comments
  tags_collection = mdb.tags
  goaway_collection = mdb.goaway
  follow_collection = mdb.follow
  #print('mongodb tweets_top1 collection size:', tweets_top1.count())
  #print('mongodb tweets_top7 collection size:', tweets_top7.count())
  #print('mongodb tweets_top30 collection size:', tweets_top30.count())
  print('mongodb comments collection size:', comments.count())
  print('mongodb tags collection size:', tags_collection.count())
  print('mongodb goaway collection size:', goaway_collection.count())
  print('mongodb follow collection size:', follow_collection.count())
```

and I get the following output:
```
carytekiMacBook-Pro:arxiv-sanity-preserver-master cary$ python serve.py
//anaconda/lib/python3.5/site-packages/flask_limiter/extension.py:134: UserWarning: Use of the default `get_ipaddr` function is discouraged. Please refer to https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration
  UserWarning
Namespace(num_results=200, port=5000, prod=False)
loading the paper database db2.p
loading tfidf_meta tfidf_meta.p
loading paper similarities sim_dict.p
loading user recommendations user_sim.p
loading serve cache... serve_cache.p
connecting to mongodb...
Traceback (most recent call last):
  File "serve.py", line 696, in <module>
    print('mongodb comments collection size:', comments.count())
  File "//anaconda/lib/python3.5/site-packages/pymongo/collection.py", line 1394, in count
    return self._count(cmd, collation)
  File "//anaconda/lib/python3.5/site-packages/pymongo/collection.py", line 1344, in _count
    with self._socket_for_reads() as (sock_info, slave_ok):
  File "//anaconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "//anaconda/lib/python3.5/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "//anaconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "//anaconda/lib/python3.5/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "//anaconda/lib/python3.5/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "//anaconda/lib/python3.5/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
```

but if I comment out all of the `comments.count()`, `tags_collection.count()`, `goaway_collection.count()`, `follow_collection.count()` lines, the output is:
```
carytekiMacBook-Pro:arxiv-sanity-preserver-master cary$ python serve.py
//anaconda/lib/python3.5/site-packages/flask_limiter/extension.py:134: UserWarning: Use of the default `get_ipaddr` function is discouraged. Please refer to https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration
  UserWarning
Namespace(num_results=200, port=5000, prod=False)
loading the paper database db2.p
loading tfidf_meta tfidf_meta.p
loading paper similarities sim_dict.p
loading user recommendations user_sim.p
loading serve cache... serve_cache.p
connecting to mongodb...
starting flask!
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

but when I open browser and type in http://0.0.0.0:5000/ and press `<Enter>`,  the page says
```html
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
and the output in the terminal becomes
```
[2017-08-16 11:48:14,221] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "//anaconda/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "//anaconda/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "//anaconda/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "//anaconda/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "//anaconda/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "serve.py", line 252, in intmain
    msg='Showing most recent Arxiv papers:')
  File "serve.py", line 215, in default_context
    top_papers = encode_json(papers, args.num_results)
  File "serve.py", line 199, in encode_json
    struct['num_discussion'] = comments.count({ 'pid': p['_rawid'] })
  File "//anaconda/lib/python3.5/site-packages/pymongo/collection.py", line 1394, in count
    return self._count(cmd, collation)
  File "//anaconda/lib/python3.5/site-packages/pymongo/collection.py", line 1344, in _count
    with self._socket_for_reads() as (sock_info, slave_ok):
  File "//anaconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "//anaconda/lib/python3.5/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "//anaconda/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "//anaconda/lib/python3.5/site-packages/pymongo/mongo_client.py", line 868, in _get_socket
    server = self._get_topology().select_server(selector)
  File "//anaconda/lib/python3.5/site-packages/pymongo/topology.py", line 214, in select_server
    address))
  File "//anaconda/lib/python3.5/site-packages/pymongo/topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused
127.0.0.1 - - [16/Aug/2017 11:48:14] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [16/Aug/2017 11:48:14] "GET /favicon.ico HTTP/1.1" 200 -
```

**Comment by shencebebetterme** [comment]
Solved! 
the reason is that mongodb is not installed, use `brew install mongodb` to install, and launch according to [the correct way to start a mongo service](https://stackoverflow.com/questions/5596521/what-is-the-correct-way-to-start-a-mongod-service-on-linux-os-x)
